version: "2"

services:

  rancher-server:
    image: rancher/server:stable
    restart: always

  rancher-ssl:
    image: dictcp/rancher-ssl
    ports:
      - "80:80"
      - "443:443"
    environment:
      EMAIL: ${ADMIN_EMAIL}
      DOMAIN: ${DOMAIN_NAME}
    links:
      - rancher-server
    restart: always
